# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(name:"Sydney")

Day.create(name:"Monday", user_id:1)
Day.create(name:"Tuesday", user_id:1)
Day.create(name:"Wednesday", user_id:1)
Day.create(name:"Thursday", user_id:1)
Day.create(name:"Friday", user_id:1)
Day.create(name:"Saturday", user_id:1)
Day.create(name:"Sunday", user_id:1)

Mealtime.create(name:"Breakfast", day_id:1)
Mealtime.create(name:"Lunch", day_id:1)
Mealtime.create(name:"Dinner", day_id:1)
Mealtime.create(name:"Breakfast", day_id:2)
Mealtime.create(name:"Lunch", day_id:2)
Mealtime.create(name:"Dinner", day_id:2)
Mealtime.create(name:"Breakfast", day_id:3)
Mealtime.create(name:"Lunch", day_id:3)
Mealtime.create(name:"Dinner", day_id:3)
Mealtime.create(name:"Breakfast", day_id:4)
Mealtime.create(name:"Lunch", day_id:4)
Mealtime.create(name:"Dinner", day_id:4)
Mealtime.create(name:"Breakfast", day_id:5)
Mealtime.create(name:"Lunch", day_id:5)
Mealtime.create(name:"Dinner", day_id:5)
Mealtime.create(name:"Breakfast", day_id:6)
Mealtime.create(name:"Lunch", day_id:6)
Mealtime.create(name:"Dinner", day_id:6)
Mealtime.create(name:"Breakfast", day_id:7)
Mealtime.create(name:"Lunch", day_id:7)
Mealtime.create(name:"Dinner", day_id:7)

Food.create(name:"Oatmeal", mealtime_id:1, calories:300)
Food.create(name:"Kale Salad", mealtime_id:2, calories:700)
Food.create(name:"Mac n Cheese", mealtime_id:3, calories:800)
Food.create(name:"Almond Butter Toast", mealtime_id:4, calories:400)
Food.create(name:"Poke Bowl", mealtime_id:5, calories:500)
Food.create(name:"Caesar Salad", mealtime_id:6, calories:500)
Food.create(name:"Yogurt", mealtime_id:7, calories:500)
Food.create(name:"Salad", mealtime_id:8, calories:200)
Food.create(name:"Steak", mealtime_id:9, calories:500)
Food.create(name:"Cinnemon Roll", mealtime_id:10, calories:0)
Food.create(name:"Sandwich", mealtime_id:11, calories:200)
Food.create(name:"Grill Cheese", mealtime_id:12, calories:800)
Food.create(name:"Avocado Toast", mealtime_id:13, calories:800)
Food.create(name:"Pizza", mealtime_id:14, calories:200)
Food.create(name:"Grill Cheese", mealtime_id:15, calories:800)
Food.create(name:"Oatmeal", mealtime_id:16, calories:800)
Food.create(name:"Salad", mealtime_id:17, calories:300)
Food.create(name:"Tomato Soup", mealtime_id:18, calories:700)
Food.create(name:"Redbull", mealtime_id:19, calories:800)
Food.create(name:"Redbull", mealtime_id:19, calories:800)
Food.create(name:"Redbull", mealtime_id:20, calories:800)
Food.create(name:"Redbull", mealtime_id:20, calories:800)
Food.create(name:"Redbull", mealtime_id:21, calories:800)
Food.create(name:"Redbull", mealtime_id:21, calories:800)
